=== ProdatoAnalytics/TomcatDemo/TomcatDemo/src/main/webapp/WEB-INF/hints/TipsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.org/NewXMLSchema"
    xmlns:tns="http://www.example.org/NewXMLSchema"
    elementFormDefault="qualified">

    <element name="tips">
        <complexType>
            <sequence>
                <element name="title" type="string" />
                <element name="description" type="string"
                    minOccurs="0" />
                <element name="tip">
                    <complexType>
                        <sequence>
                            <element name="topic" type="string" />
                            <element name="description"
                                type="string" minOccurs="0" />
                            <element name="locations"
                                maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                    <element name="location"
                                type="string" maxOccurs="unbounded" />
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>


</schema>

=== ProdatoAnalytics/TomcatDemo/TomcatDemo/src/main/webapp/WEB-INF/hints/01_RootTips.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tips xmlns:tns="http://www.example.org/NewXMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/NewXMLSchema TipsSchema.xsd ">
    <tns:title>Root</tns:title>
    <tns:description>Tips f√ºr Sachen, die im allgemeinen Teil des Projekts liegen</tns:description>
    <tns:tip>
        <tns:topic>JAXB</tns:topic>
        <tns:description>Auslesen von XML-Dateien mit Hilfe von automatisch generierten Pojos (Stichwort: XJC)</tns:description>
        <tns:locations>
            <tns:location>MenuLoader.java</tns:location>
            <tns:location>NewXMLSchema.xsd</tns:location>
            <tns:location>menufiles</tns:location>
        </tns:locations>
    </tns:tip>

</tns:tips>

=== ProdatoAnalytics/TomcatDemo/TomcatDemo/src/main/webapp/WEB-INF/hints/02_ServletTips.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tips xmlns:tns="http://www.example.org/NewXMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/NewXMLSchema TipsSchema.xsd ">
    <tns:title>Servlet</tns:title>
    <tns:description>Tips für Sachen, die nur Servlets betreffen</tns:description>
    <tns:tip>
        <tns:topic>doPost</tns:topic>
        <tns:description>Nicht nur ausschließlich GET (Stichwort: Form, POST, Parameter)</tns:description>
        <tns:locations>
            <tns:location>RedirectionServlet.java</tns:location>
        </tns:locations>
    </tns:tip>

</tns:tips>
