=== ProdatoAnalytics/TomcatDemo/TomcatDemo/src/main/webapp/kochrezept/kochrezept.dtd
<!ENTITY % textelement
 " (#PCDATA|LINK)*"
>

<!ELEMENT MAIN (KOMMENTARE*,INHALT,TAGEBUCH,FAECHER*,QUELLEN)>
   <!ATTLIST MAIN title CDATA #REQUIRED>
   <!ATTLIST MAIN buttons CDATA #REQUIRED>
   <!ATTLIST MAIN images CDATA #REQUIRED>

<!ELEMENT KOMMENTARE (KOMMENTAR*)>
<!ELEMENT KOMMENTAR %textelement;>

<!ELEMENT INHALT (INHALTEINTRAG*)>
<!ELEMENT INHALTEINTRAG (#PCDATA)>
   <!ATTLIST INHALTEINTRAG link IDREF #REQUIRED>


<!ELEMENT TAGEBUCH (EINTRAG*)>
   <!ATTLIST TAGEBUCH linkid ID #REQUIRED>
<!ELEMENT EINTRAG (ZEILE*)>
   <!ATTLIST EINTRAG datum CDATA #REQUIRED>
<!ELEMENT ZEILE %textelement;>

<!ELEMENT LINK (#PCDATA)>
   <!ATTLIST LINK href CDATA #REQUIRED>

<!ELEMENT FAECHER (FACH*)>
<!ELEMENT FACH (KAPITEL*)>
   <!ATTLIST FACH name CDATA #REQUIRED>
   <!ATTLIST FACH linkid ID #REQUIRED>

<!ELEMENT KAPITEL (BLATT*)>
   <!ATTLIST KAPITEL name CDATA #REQUIRED>

<!ELEMENT BLATT (#PCDATA|LINK)*>
   <!ATTLIST BLATT link CDATA #IMPLIED>
   <!ATTLIST BLATT name CDATA #REQUIRED>
   <!ATTLIST BLATT rang (gruen|gelb|rot|grau) #REQUIRED>
   <!ATTLIST BLATT status CDATA #IMPLIED>

<!ELEMENT QUELLEN (QUELLE*)>
   <!ATTLIST QUELLEN linkid ID #REQUIRED>
<!ELEMENT QUELLE %textelement;>

=== ProdatoAnalytics/TomcatDemo/TomcatDemo/src/main/webapp/kochrezept/index.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>

<?xml-stylesheet type="text/xsl" href="kochrezept.xsl" ?>
<!DOCTYPE MAIN SYSTEM "kochrezept.dtd">

<MAIN title="Michaels Mitschriften und Kochrezepte" buttons="./Buttons/" images="./Images/">

   <KOMMENTARE>
      <KOMMENTAR>
      Hallo! 
      </KOMMENTAR>
      <KOMMENTAR>
      Hier möchte ich im Laufe der nächsten Wochen eine Sammlung für Mitschriften und kurze
      Notizen für die zweite Hälfte Vordiplomsprüfung aufbauen.
      </KOMMENTAR>
      <KOMMENTAR>
      Für Kommentare / Korrekturen bin ich erreichbar unter 
      <LINK href="mailto:m_lehmeier@gmx.de">m_lehmeier@gmx.de</LINK>.
      </KOMMENTAR>
      <KOMMENTAR>
      Die Mitschriften der Übungen in TI3 und WS1 werden nur eine Zeit lang
      erreichbar sein, bis mir der Platz ausgeht. Wer sie danach noch braucht
      soll mich anmailen.
      </KOMMENTAR>
   </KOMMENTARE>

	<INHALT>
		<INHALTEINTRAG link="tagebuch">
			Tagebuch
		</INHALTEINTRAG>
		<INHALTEINTRAG link="m12">
			Mathe 1 und 2
		</INHALTEINTRAG>
		<INHALTEINTRAG link="m3">
			Mathe 3
		</INHALTEINTRAG>
		<INHALTEINTRAG link="wr1">
			Wahrscheinlichkeitsrechnung 1
		</INHALTEINTRAG>
		<INHALTEINTRAG link="ti1">
			Theoretische Informatik 1
		</INHALTEINTRAG>
		<INHALTEINTRAG link="ti2">
			Theoretische Informatik 2
		</INHALTEINTRAG>
		<INHALTEINTRAG link="ti3">
			Theoretische Informatik 3
		</INHALTEINTRAG>
		<INHALTEINTRAG link="quellen">
			Quellen
		</INHALTEINTRAG>
	</INHALT>

   <TAGEBUCH linkid="tagebuch">
      <EINTRAG datum="1. April 2005">
         <ZEILE>
            Über die TI-Klausur möchte ich mich nicht äußern. Zumindest nicht, bis ich das Ergebnis habe. Und das will ich gar nicht habe, bis Mathe vorüber ist.
         </ZEILE>
         <ZEILE>
            Daß es kein Update hier gegeben hat, liegt vor allem daran, daß ich viel Zeit mit Übungen verbracht habe und die Stofffülle schlicht nicht so groß war. Allerdings ist mir später aufgefallen, daß vor allem im Mathe 3 Teil meine Zettel zu wünschen übrig ließen. Deshalb habe ich nach meinem ersten Übungsdurchlauf damit begonnen, sie noch mal zu schreiben. Deshalb auch erst das späte Update. Wahrscheinlichkeitsrechnung habe ich jetzt viel mehr kapiert, aber an den Zetteln hat das nichts geändert. Deshalb keine Neuerungen hier.
         </ZEILE>
         <ZEILE>
            Aber wie gesagt, ich habe das gesamte Mathe 3 ausgetauscht. Viel Spaß!
         </ZEILE>
      </EINTRAG>
      <EINTRAG datum="7. März 2005">
         <ZEILE>
            Letztes Update.
         </ZEILE>
         <ZEILE>
            Bitte schaut euch Insertionsort an. Ich habe keine Ahnung wie das passieren konnte, aber die bisherige Methode ist nicht richtig!
         </ZEILE>
      </EINTRAG>
      <EINTRAG datum="3. März 2005">
         <ZEILE>
            Allzuviel kommt nicht mehr dazu. Ich bin jetzt aber mit TI2 durch.
         </ZEILE>
         <ZEILE>
            Lücken sind geblieben. Den Bereich Termalgebren habe ich vollkommen weggelassen, da mir hier das Skript doch ab dem 2. Drittel etwas konfus schien und auch teilweise widersprüchlich. Jedenfalls sehe ich nicht, wie man hier groß sich auf Klausuraufgaben vorbereiten kann.
         </ZEILE>
      </EINTRAG>
     <EINTRAG datum="23. Februar 2005">
         <ZEILE>
            Ich habe meinen Lernstoff vor allem auf Karteikarten verlegt, die ich (noch?) nicht einscanne. Deshalb weiterhin wenig Zettel.
         </ZEILE>
         <ZEILE>
            TI1 betrachte ich jetzt als abgeschlossen. Die nächste Woche hoffe ich mit TI2 durchzukommen. Mal sehen wie ich dann dastehe.
         </ZEILE>
      </EINTRAG>
      <EINTRAG datum="10. Februar 2005">
         <ZEILE>
            Leider sind die Prüfungen für mich nicht positiv ausgeganen, deshalb führe ich diese Seite jetzt weiter.
         </ZEILE>
         <ZEILE>
            Es kommen viele neue Blätter hinzu, aber ich habe auch viele überarbeitet. Entweder weil ich jetzt mehr darüber weiß oder weil sie nicht mehr gut genug sind. Ein paar hatten auch haarsträubende Fehler, aber die Gefahr besteht nun mal immer.
         </ZEILE>
      </EINTRAG>
   </TAGEBUCH>

   <FAECHER>
      <FACH name="Mathematik 1-2" linkid="m12">
         <KAPITEL name="Lineare Algebra">
            <BLATT link="lgs_tricks.gif" name="Tricks mit linearen Gleichungssystemen" rang="gruen">
               Hat mit Gauss-Eliminiation zu tun.
            </BLATT>
            <BLATT link="horner_schema.gif" name="Horner Schema" rang="gruen">
               Zur schnellen Ausrechnung von linearen Gleichungssystemen
            </BLATT>
            <BLATT link="komplexe_zahlen.gif" name="Komplexe Zahlen" rang="gruen">
               Kann man viel damit machen, aber für uns ist das jetzt nicht so wichtig. Gut, wenn man aber nachschlagen kann.
            </BLATT>
            <BLATT link="vektorrechnung.gif" name="Vektorrechnung" rang="gelb">
               In Mathe 3 ziemlich wichtig. Sollte man aber schon können.
            </BLATT>
            <BLATT link="matrizen.gif" name="Matrizen" rang="gruen">
               Ist recht wichtig, aber Grundwissen und nur mäßig interessant für zweite Hälfte Vordiplom.
            </BLATT>
            <BLATT link="determinanten.gif" name="Determinanten" rang="gelb">
               Grundwissen, wird auch in Mathe 3 gebraucht.
            </BLATT>
            <BLATT link="eigenwerte.gif" name="Eigenwerte und Eigenvektoren" rang="gelb">
               Sind bei Differentialgleichungen wichtig.
            </BLATT>
            <BLATT link="limes.gif" name="Limes mit l'Hospital" rang="gruen">
               Keine Ahnung in wie weit das wichtig wäre.
            </BLATT>
            <BLATT link="limes_polynombruechen.gif" name="Limes von Polynombrüchen" rang="gruen">
               Eine kleine Ergänzung zum anderen Limes-Blatt
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Differentialrechnung">
            <BLATT link="differenzieren.gif" name="Differenzieren" rang="rot">
               Die wichtigen Regeln kurzgefasst.
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Rüstzeug für Integralrechnung">
            <BLATT link="polynomdivision.gif" name="Polynomdivision" rang="gruen">
               Braucht man für Partialbruchzerlegung.
            </BLATT>
            <BLATT link="partialbruchzerlegung.gif" name="Partialbruchzerlegung" rang="gruen">
               So zerhackt man kompliziertere Polynome in leichter zu integrierende Teilstücke. Leider sehr zeitaufwändig.
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Integralrechnung">
            <BLATT link="integrieren.gif" name="Integrieren" rang="rot">
               Die einfachen Integrationsregeln ohne Substitution
            </BLATT>
            <BLATT link="integral_vorgehensweise.gif" name="Vorgehensweise bei Integralrechnung" rang="rot">
               So gehe ich immer vor! Bei jeder Integration.
            </BLATT>
            <BLATT link="substitution.gif" name="Integration durch Substitution" rang="rot">
               Sehr Wichtig! Muß man immer zumindest im Hinterkopf haben. Vorher hatte ich die Wichtigkeit unterschätzt, jetzt nicht mehr.
            </BLATT>
            <BLATT link="partielle_integration.gif" name="Partielle Integration" rang="gelb">
               Kann leider nicht sehr oft verwendet werden und dann gibt es oft sehr hässliche Ergebnisse. Aber manchmal der letzte Notnagel.
            </BLATT>
            <BLATT link="bestimmte_integrale.gif" name="Bestimmte Integrale" rang="gelb">
               Ist oft der letzte Schritt. Ist aber einfach und leicht zu merken.
            </BLATT>
         </KAPITEL>
      </FACH>
   
      <FACH name="Mathematik 3" linkid="m3">
         <KAPITEL name="Mehrdimensionale Differenzialrechnung">
            <BLATT link="2_01_Richtungsableitung.gif" name="Richtungsableitung" rang="grau" status="neu">
               Es gibt mehrere Arten, die zu ermitteln. Im Zweifelsfall bei der einfachsten bleiben und den Gradient ermitteln.
            </BLATT>
            <BLATT link="2_02_StetigkeitRn.gif" name="Stetigkeit" rang="grau" status="neu">
               Was ist zu tun, wenn man die Stetigkeit in einer mehrdimensionalen Funktion an einem Punkt feststellen will.
            </BLATT>
            <BLATT link="2_03_KritischePunkte.gif" name="Kritische Punkte aufspüren" rang="grau" status="neu">
               Wo können Minima/Maxima liegen? Dort wo die Steigung 0 ist.
            </BLATT>
            <BLATT link="2_04_KritischePunkteUntersuchen.gif" name="Kritische Punkte untersuchen" rang="grau" status="neu">
               Außschließen, daß es sich um einen Sattelpunkt handelt. Geht nicht immer, leider.
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Kurven">
            <BLATT link="2_05_KurvenSchnittwinkel.gif" name="Schnittwinkel von Kurven" rang="grau" status="neu">
               Man hat zwei Kurfen die sich schneiden. Mit welchem Winkel?
            </BLATT>
            <BLATT link="2_06_Bogenlaenge.gif" name="Bogenlänge einer Kurve" rang="grau" status="neu">
               Wie lange ist ein bestimmter Abschnitt einer Kurve?
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Differentialrechnung Rn->Rm">
            <BLATT link="2_07_DifferentiationRnRm.gif" name="Differentialrechnung von Rn nach Rm" rang="grau" status="neu">
               Enthält unter anderem die Jacobi-Matrix.
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Mehrdimensionale Integration">
            <BLATT link="2_08_IntegrationRn.gif" name="Integration" rang="grau" status="neu">
               Nicht so schwer, wenn man mal durchblicht. Vor allem die Integrationssbereiche sind wichtig. Da darf man nicht durcheinanderkommen.
            </BLATT>
         </KAPITEL>
         <KAPITEL name="Differentialgleichungen 1. Ordnung">
